### ISSUE TITLE
vanilla Java / jogl support?

### ISSUE THREAD

**Issue by diroru** [leadedge/SpoutProcessing#3]
Hello,
thanks for the awesome library! 

Normally, it shouldn't be a stretch, but i can't seem to use it in java.

The following error occurs under windows 10, 64-bit with the latest jdk(1.8.0_144):
`Exception in thread "main" java.lang.UnsatisfiedLinkError: helloSpout.JNISpout.init()J
          at helloSpout.JNISpout.init(Native Method)`

The native dll are being loaded but none of the methods are found. Tried a lot of things, a different jdk (1.8.0_51) version, java language levels, etc. but nothing worked. 

Of course, i am intent on adapting the function logics to suit JOGL.

Do you have an idea why this could be happening and how it could be resolved?

Many thanks in advance,
cheers!

**Comment by leadedge** [comment]
The JNI library was started by using Javac and Javah but had some problems and was rewritten for Eclipse. I had a lot of help with this and so cannot directly answer your question. But perhaps you can get some idea from the sequence of events, where several people have made comments -

http://spout.zeal.co/forums/topic/developing-processing-programs-using-spout-in-eclipse-default-package-issue/

**Comment by diroru** [comment]
Thank you very much for your swift reply!

Will follow the link, hopefully it will lead me to a solution.

Again, many thanks for the awesome library and cheers!

**Comment by diroru** [comment]
A little follow-up: the issue was that the `JNISpout.java` needs to be inside a package called `spout` that is in the project root (so `spout.JNISpout` works, but `foo.spout.JNISpout` will not be recognised). If you wish to deviate from that, you will most probably need to rebuild the dlls yourself using `javah` and the execute the other compilation steps (haven't really dug into that matter). **NB** You will probably have to change the method visibility from `protected` to `public`.

**Comment by leadedge** [comment]
Thanks for that. 

This was the original issue and Ilias Bergstrom resolved it using a wrapper and reflection method. Unfortunately I could not get the Eclipse project working and had to set it aside. Martin Froelich continued the project and the classes were put inside a package. But I don't have sufficient understanding to know the details that you refer to.

Importantly, since then I made a have introduced a spout object pointer, so that multiple objects can be created and used withing the same sketch.

I guess as you suggest, the entire project could be reconfigured to enable use of javac and javah once more, but I am reluctant to change anything in the Eclipse project since the library is stable.

However, it might be possible to make a suitable dll specifically for Java. The project originally used a dll built with javac and javah and all that code is still archived if you would like to see it. It is out of date but the core might be used to create a suitable dll. Also, although the current JNI dll is not on Github, you are welcome to have a copy if you would like to work on it. Just email me and I will sort out a download for you.
