### ISSUE TITLE
Processing on Raspberry 

### ISSUE THREAD

**Issue by lyon470** [leadedge/SpoutProcessing#5]
Hello,
i have installed Processing on an Raspberry Pi and try to run SpoutSender.
But i get an issue with Java.
It Shows me "java.lang.UnsatisfiedLinkError" and Processing need to be in 64bit.

Is the SpoutProcessing only with 64bit compatible ?

Thanks

**Comment by leadedge** [comment]
SpoutProcessing will detect and load either the 32bit or 64bit library. But it is for Windows only and is also NVIDIA hardware dependent. I believe you can use Windows 10 IoT Core with the Raspberry Pi and there is a chance that Spout might work with in memoryshare mode, but I have no system to test and develop.

**Comment by lyon470** [comment]
Is there another way to receive Spout on an Raspberry Pi ?

**Comment by leadedge** [comment]
I am afraid not.

**Comment by lyon470** [comment]
This is the complete error message.

Spout 32bit v2.0.6.0 - Java 1.8.0_202
java.lang.UnsatisfiedLinkError: no JNISpout_32 in java.library.path
at processing.opengl.PSurfaceJOGL$2.run(PSurfaceJOGL.java:408)
at java.lang.Thread.run(Thread.java:748)
UnsatisfiedLinkError: no JNISpout_32 in java.library.path
UnsatisfiedLinkError: no JNISpout_32 in java.library.path
A library relies on native Code that's not available.
Or only works properly when the Sketch is run as a 64-bit application.


I understand this that the Spout Library is not in the right Java folder.
Do i Need to copy the library in a specific Folder ?

**Comment by leadedge** [comment]
Look in your processing sketchbook folder for : ..\libraries\spout\library\
In there you should find both JNISpout_32.dll and JNISpout_64.dll. They are copied there when you install "Spout for Processing" from the contribution manager using  Sketch > Import Library. Processing uses it's own version of Java. If a sketch runs at all, the paths are established. I still do not know what operating system you are using. If it is Windows there is some chance in memoryshare mode, otherwise not.
